/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d9dadc',
        secondary: '#5b5d72',
        'on-secondary-fixed': '#181a2c',
        'surface-container-low': '#f2f4f6',
        tertiary: '#453000',
        'on-surface-variant': '#464651',
        'on-secondary-container': '#616378',
        'error-container': '#ffdad6',
        'surface-tint': '#5355ab',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#261900',
        'secondary-fixed-dim': '#c4c5dd',
        'on-primary-fixed-variant': '#3a3c91',
        'on-primary': '#ffffff',
        'surface-variant': '#e1e2e4',
        'primary-fixed': '#e1e0ff',
        'secondary-fixed': '#e0e0fa',
        'inverse-on-surface': '#f0f1f3',
        'surface-container': '#edeef0',
        'on-secondary': '#ffffff',
        'primary-container': '#3e4095',
        'on-tertiary-container': '#dcb56c',
        'outline-variant': '#c7c5d3',
        primary: '#26277d',
        'primary-fixed-dim': '#c0c1ff',
        'on-error': '#ffffff',
        'on-primary-container': '#b2b3ff',
        'on-secondary-fixed-variant': '#444559',
        'on-tertiary-fixed-variant': '#5d4201',
        'on-background': '#191c1e',
        'tertiary-container': '#614604',
        'on-primary-fixed': '#090467',
        'on-surface': '#191c1e',
        'secondary-container': '#e0e0fa',
        'inverse-surface': '#2e3132',
        'surface-bright': '#f8f9fb',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        outline: '#777683',
        'tertiary-fixed': '#ffdea5',
        'surface-container-high': '#e7e8ea',
        surface: '#f8f9fb',
        'tertiary-fixed-dim': '#e9c176',
        'inverse-primary': '#c0c1ff',
        'on-tertiary': '#ffffff',
        background: '#f8f9fb',
        'surface-container-highest': '#e1e2e4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      boxShadow: {
        ambient: '0 30px 60px rgba(38,39,125,0.08)',
        'ambient-sm': '0 10px 30px rgba(38,39,125,0.05)',
        'ambient-lg': '0 40px 80px rgba(38,39,125,0.10)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.7s ease-out forwards',
        'fade-in': 'fade-in 0.5s ease-out forwards',
      },
    },
  },
  plugins: [],
};
